# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_title', models.CharField(max_length=500)),
                ('class_description', models.CharField(max_length=1000)),
                ('class_logo', models.CharField(max_length=500)),
                ('class_level', models.IntegerField(default=0)),
                ('class_category', models.CharField(max_length=50)),
            ],
        ),
    ]
