# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='class_category',
            field=models.IntegerField(default=0),
        ),
    ]
